### ISSUE TITLE
Redis for windows

### ISSUE THREAD

**Issue by SychevIgor** [lawrencegripper/RedisOnSerivceFabric-Example#3]
Hello,
Thank you for your job. 

Microsoft moved Redis for Windows to Archive few years ago. https://github.com/MicrosoftArchive/redis

One of devs in my team missed this fact and start implementing cache for service fabric using your approach.

Could you please, somehow highlight in a readme file, that this sample is no longer valid, since redis for windows de factor not supported? 
Otherwise, other developers can make the same mistake and waiste their time.

Thank you in advance!

**Comment by lawrencegripper** [comment]
Sure, would you be happy to put in the pull request to update the readme with some details?

**Comment by SychevIgor** [comment]
I can't drop this repo or move it to archive.

**Comment by lawrencegripper** [comment]
I understand - was responding to your suggestion.

> Could you please, somehow highlight in a readme file, that this sample is no longer valid, since redis for windows de factor not supported?

**Comment by lawrencegripper** [comment]
Preface: I woke up in a bad mood and re-reading your original comments I think the below is unjustified - sorry

~~As a more meta point: I know this was unintentional but the tone in which you've engaged with me here as left me feeling pretty low.~~

~~Suggesting that I've wasted your developers time makes me feel bad.~~

~~> Otherwise, other developers can make the same mistake and waiste their time.~~

~~Offering a solution that you can provide then not doing it puts work back on me.~~

There are a couple of things I need to do. I'd like to setup a script to automatically mark old stuff as old on github to warn people. I also probably need to be more thick skinned.

~~Ultimately while this can seem really minor they can happen a lot when you've put a lot of work out there in the OSS world and they become a 'death by a thousand cuts'. My aim was to put something out there to help others and I did that 3 years ago, between other projects and different commitments I've not managed to keep things up-to-date but that's by no means intentional or through lack of effort (only so much time in the day)~~

~~It's [hard to put out stuff which is perfect](https://github.com/SychevIgor/azure_mongo_ubuntu/issues/1) and even harder to maintain it over time but we can try and engage positively and thoughtfully with others [to help them fix things](https://github.com/SychevIgor/azure_mongo_ubuntu/issues/1#issuecomment-470023256) where possible.~~

Thanks for raising an issue to fix this one up and helping others.
